version: '3'

services:
  mysql:
    image: mysql:8.0.30-debian
    container_name: mysql
    platform: linux/x86_64
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_db
      MYSQL_PASSWORD: root
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
    ports:
      - 3306:3306
